"""Add telegram_group bank info

Revision ID: 3fc9afc29fb9
Revises: 
Create Date: 2026-04-21 22:14:57.578517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fc9afc29fb9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('telegram_group', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('number_bank', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('bank_name', sa.String(), nullable=True))
    op.add_column('employee', sa.Column('telegram_group', sa.String(), nullable=True))
    op.drop_constraint(op.f('investments_investment_code_key'), 'investments', type_='unique')
    op.create_index(op.f('ix_investments_investment_code'), 'investments', ['investment_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investments_investment_code'), table_name='investments')
    op.create_unique_constraint(op.f('investments_investment_code_key'), 'investments', ['investment_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('employee', 'telegram_group')
    op.drop_column('customers', 'bank_name')
    op.drop_column('customers', 'number_bank')
    op.drop_column('customers', 'telegram_group')
    # ### end Alembic commands ###
