"""add product transactions

Revision ID: da33c2e0368f
Revises: 3fc9afc29fb9
Create Date: 2026-04-21 23:54:37.452680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da33c2e0368f'
down_revision: Union[str, Sequence[str], None] = '3fc9afc29fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=True),
    sa.Column('material_type', sa.String(), nullable=True),
    sa.Column('storage_id', sa.UUID(), nullable=True),
    sa.Column('storage_name', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('debt', sa.Float(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_transactions')
    # ### end Alembic commands ###
